baseurl = "https://forestry.io"
copyright = ""
defaultContentLanguage = "en"
destination = "../dist/"
enableEmoji = true
enableRobotsTXT = true
languageCode = "en"
metaDataFormat = "yaml"
paginate = 10
pluralizeListTitles = false
relativeURLs = false
title = "Forestry.io"
[blackfriday]
angledQuotes = false
hrefTargetBlank = false
latexDashes = true
plainIDAnchors = true
[[menu.docs]]
identifier = "git-sync"
name = "Git Sync"
url = "/docs/git-sync"
weight = 7
[[menu.docs]]
identifier = "welcome"
name = "Welcome"
url = "/docs/welcome"
weight = 6
[[menu.docs]]
identifier = "other"
name = "Other"
url = ""
[[menu.footer]]
identifier = "company"
name = "Company"
weight = 5
[[menu.footer]]
identifier = "product"
name = "Product"
weight = 3
[[menu.main]]
identifier = "signup"
name = "Sign up"
url = "https://app.forestry.io/signup"
weight = 8
[[menu.main]]
identifier = "userdashboard"
name = "Dashboard"
url = "https://app.forestry.io/dashboard"
weight = 7
[[menu.main]]
identifier = "login"
name = "Login"
url = "https://app.forestry.io/login"
weight = 6
[[menu.main]]
identifier = "useraccount"
name = "My Account"
url = "https://app.forestry.io/settings"
weight = 5
[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
path = "/"
[outputFormats.OpenSearch]
baseName = "opensearch"
isPlainText = true
mediaType = "application/xml"
path = "/"
[outputs]
home = ["HTML", "RSS", "OpenSearch", "Algolia"]
[params]
dateformat = "January 2, 2006"
description = "  Write an awesome description for your new site here. You can edit this\\\n  line in config.yml. It will appear in your document head meta (for\\\n  Google search results) and in your RSS feed description.\\\n  "
ghrepo = "https://github.com/forestryio/forestry.io"
ghrepo_edit = "https://github.com/forestryio/forestry.io/edit/master/hugo/content/"
ghrepo_new = "https://github.com/forestryio/forestry.io/issues/new"
gtmid = "GTM-KL5HP9Q"
images = ["images/gohugoio-card.png"]
mixpanelid = "8aaf5d792dd5bf875adae0b2adac8900"
[params.cloudinary]
cloud_name = "forestry-demo"
use_upload = false
[params.cloudinary.lazysizes]
enabled = true
[params.cloudinary.presets.default]
fallback_width = 960
max_width = 1200
min_width = 320
sizes = "100vw"
steps = 5
[related]
includeNewer = true
threshold = 10
toLower = true
[[related.indices]]
name = "Section"
weight = 200
[[related.indices]]
name = "keywords"
weight = 150
[[related.indices]]
name = "categories"
weight = 150
[[related.indices]]
name = "tags"
weight = 100
[[related.indices]]
name = "date"
pattern = "2006"
weight = 10
[social]
email = "support@forestry.io"
slack = "https://t.co/OANAJYol8Y"
twitter = "forestryio"
[taxonomies]
author = "authors"
category = "categories"
tag = "tags"
