---
upload_path: "/hugo/static/uploads/:year:/:month:"
frontmatter_file_url_template: "/uploads/:year:/:month:"
body_file_url_template: "/uploads/:year:/:month:"
new_page_extension: md
auto_deploy: false
admin_path: "/admin"
webhook_url: 
sections: 
version: 0.38.1
build:
  preview_command: yarn build
  publish_command: yarn preDeploy
  output_directory: dist
