service:
  name: atomic-algolia

provider:
  name: webtasks
  environment: 
    ALGOLIA_APP_ID: "${env:ALGOLIA_APP_ID, opt:ALGOLIA_APP_ID, self:custom.ALGOLIA_APP_ID}"
    ALGOLIA_ADMIN_KEY: "${env:ALGOLIA_APP_ID, opt:ALGOLIA_APP_ID, self:custom.ALGOLIA_ADMIN_KEY}"
    INDEXES: ${file(./indexes.js)}

custom:
  stage: "${opt:stage, self:provider.stage}"
  ALGOLIA_APP_ID: ${file(./env.yml):ALGOLIA_APP_ID}
  ALGOLIA_ADMIN_KEY: ${file(./env.yml):ALGOLIA_ADMIN_KEY}

functions:
  main:
    handler: functions/basic
    events:
      - schedule: rate(1 day)
  webhook:
    handler: functions/webhook

plugins:
  - '@webtask/serverless-webtasks'